server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com:
      netflix: 
        eureka: OFF
        discovery: OFF
